# Generated by Django 4.2 on 2023-12-13 22:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import app.models.base


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="B3Stock",
            fields=[
                (
                    "id",
                    app.models.base.UUIDPrimaryKeyField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("last_updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("code", models.CharField(max_length=10, verbose_name="Code")),
            ],
            options={
                "verbose_name": "B3 stock",
                "verbose_name_plural": "B3 stocks",
            },
        ),
        migrations.CreateModel(
            name="MonitoredStock",
            fields=[
                (
                    "id",
                    app.models.base.UUIDPrimaryKeyField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("last_updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "check_periodicity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="The time, in minutes, that the stock will be checked.",
                        verbose_name="Check periodicity",
                    ),
                ),
                ("superior_limit", models.PositiveSmallIntegerField(verbose_name="Superior limit")),
                ("inferior_limit", models.PositiveSmallIntegerField(verbose_name="Inferior limit")),
                (
                    "B3_stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitored_stocks",
                        to="stocks.b3stock",
                        verbose_name="B3 stock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitored_stocks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monitored stock",
                "verbose_name_plural": "Monitored stocks",
            },
        ),
        migrations.CreateModel(
            name="B3StockPrice",
            fields=[
                (
                    "id",
                    app.models.base.UUIDPrimaryKeyField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("last_updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Price"),
                ),
                (
                    "B3_monitored_stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="B3_monitored_stocks",
                        to="stocks.monitoredstock",
                        verbose_name="B3 monitored stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "B3 stock price",
                "verbose_name_plural": "B3 stock prices",
            },
        ),
    ]
